language: bash
services:
  - docker

env:
  - VERSION=1.0.2 VARIANT=
  - VERSION=1.1.0 VARIANT=

before_script:
  - version="$(awk '$2 == "OPENSSL_VERSION" { print $3; exit }' $VERSION/Dockerfile)"
  - image="$version${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "$VERSION/$VARIANT"
  - docker run --rm "$image" openssl version | fgrep "OpenSSL $version "

after_script:
  - docker images
